<?php

namespace SP\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CARepository extends EntityRepository
{
}
